.PHONY: gen mocks test testv dbtest dbtestv alltest

gen:
	go generate ./...

MOCKS=DB Mailer

mocks:
	mockery -recursive -name "$(shell echo "$(MOCKS)" | tr ' ' '|')"

test:
	go generate ./...
	go test -tags '!db' ./...

testv:
	go generate ./...
	go test -v -tags '!db' ./...

dbtest:
	go generate ./...
	go test -tags db ./...

dbtestv:
	go generate ./...
	go test -v -tags db ./...

alltest:
	go generate ./...
	go test ./...
