// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: template, language, email, data
func (_m *Mailer) Send(template string, language string, email string, data map[string]string) {
	_m.Called(template, language, email, data)
}
